-- MySQL Script generated by MySQL Workbench
-- Thu Nov  2 18:13:27 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `rut` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidoPaterno` VARCHAR(45) NOT NULL,
  `apellidoMaterno` VARCHAR(45) NOT NULL,
  `clave` VARCHAR(8) NOT NULL,
  `rol` VARCHAR(20) NOT NULL,
  `saldo` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`menu`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`menu` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `tipo` VARCHAR(45) NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidadRaciones` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`horario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `horaInicio` TIME NOT NULL,
  `cantMaxRaciones` INT NOT NULL,
  `horaFin` TIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`reserva`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`reserva` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha` TIMESTAMP NOT NULL,
  `idusuario` INT NOT NULL,
  `idmenu` INT NOT NULL,
  `idhorario` INT NOT NULL,
  PRIMARY KEY (`id`, `idusuario`, `idmenu`, `idhorario`),
  INDEX `fk_reserva_usuario_idx` (`idusuario` ASC),
  INDEX `fk_reserva_menu1_idx` (`idmenu` ASC),
  INDEX `fk_reserva_horario1_idx` (`idhorario` ASC),
  CONSTRAINT `fk_reserva_usuario`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_menu1`
    FOREIGN KEY (`idmenu`)
    REFERENCES `mydb`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reserva_horario1`
    FOREIGN KEY (`idhorario`)
    REFERENCES `mydb`.`horario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`evaluacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`evaluacion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `valoracion` FLOAT NOT NULL,
  `comentario` VARCHAR(50) NOT NULL,
  `idusuario` INT NOT NULL,
  `idmenu` INT NOT NULL,
  PRIMARY KEY (`id`, `idusuario`, `idmenu`),
  INDEX `fk_evaluacion_usuario1_idx` (`idusuario` ASC),
  INDEX `fk_evaluacion_menu1_idx` (`idmenu` ASC),
  CONSTRAINT `fk_evaluacion_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `mydb`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_evaluacion_menu1`
    FOREIGN KEY (`idmenu`)
    REFERENCES `mydb`.`menu` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
